DROP TYPE IF EXISTS UNIVERSE;

DROP TABLE IF EXISTS team;;

DROP TABLE IF EXISTS  character;

DROP TABLE IF EXISTS  super_power;

DROP TABLE IF EXISTS  game;

DROP TABLE IF EXISTS hq;

DROP TABLE IF EXISTS serie;

DROP TABLE IF EXISTS character_serie;

DROP TABLE IF EXISTS character_hq;

DROP TABLE IF EXISTS character_super_power;

DROP TABLE IF EXISTS  character_game;

DROP TABLE IF EXISTS  team_game;

DROP TABLE IF EXISTS  movie;

DROP TABLE IF EXISTS  character_movie;

DROP TABLE IF EXISTS  console_game;

DROP TABLE IF EXISTS  console;