// Code generated by MockGen. DO NOT EDIT.
// Source: log.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(ctx context.Context, err error, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, err, data)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(ctx, err, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), ctx, err, data)
}

// MockVendor is a mock of Vendor interface.
type MockVendor struct {
	ctrl     *gomock.Controller
	recorder *MockVendorMockRecorder
}

// MockVendorMockRecorder is the mock recorder for MockVendor.
type MockVendorMockRecorder struct {
	mock *MockVendor
}

// NewMockVendor creates a new mock instance.
func NewMockVendor(ctrl *gomock.Controller) *MockVendor {
	mock := &MockVendor{ctrl: ctrl}
	mock.recorder = &MockVendorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendor) EXPECT() *MockVendorMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockVendor) Send(ctx context.Context, payload []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", ctx, payload)
}

// Send indicates an expected call of Send.
func (mr *MockVendorMockRecorder) Send(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockVendor)(nil).Send), ctx, payload)
}
